export const PAINTINGS = {
  // FETCH
  FETCH_PAINTINGS_START: "FETCH_PAINTINGS_START",
  FETCH_PAINTINGS_SUCCESS: "FETCH_PAINTINGS_SUCCESS",
  FETCH_PAINTINGS_FAILURE: "FETCH_PAINTINGS_FAILURE",
  // ADD
  ADD_PAINTING_START: "ADD_PAINTING_START",
  ADD_PAINTING_SUCCESS: "ADD_PAINTING_SUCCESS",
  ADD_PAINTING_FAILURE: "ADD_PAINTING_FAILURE",
  EDIT_PAINTING: "EDIT_PAINTING",
  DELETE_PAINTING: "DELETE_PAINTING",
  VIEW_SELECTED_PAINTING: "VIEW_SELECTED_PAINTING",
  CLEAR_SELECTED_PAINTING: "CLEAR_SELECTED_PAINTING",
};
