export const PAINTINGS = {
  // FETCH
  FETCH_PAINTINGS_START: "FETCH_PAINTINGS_START",
  FETCH_PAINTINGS_SUCCESS: "FETCH_PAINTINGS_SUCCESS",
  FETCH_PAINTINGS_FAILURE: "FETCH_PAINTINGS_FAILURE",
  // ADD
  ADD_PAINTING_START: "ADD_PAINTING_START",
  ADD_PAINTING_SUCCESS: "ADD_PAINTING_SUCCESS",
  ADD_PAINTING_FAILURE: "ADD_PAINTING_FAILURE",
  // DELETE
  DELETE_PAINTING_START: "DELETE_PAINTING_START",
  DELETE_PAINTING_SUCCESS: "DELETE_PAINTING_SUCCESS",
  DELETE_PAINTING_FAILURE: "DELETE_PAINTING_FAILURE",
  // EDIT
  ENTER_EDIT_MODE: "TOGGLE_EDIT_MODE",
  EDIT_PAINTING_START: "EDIT_PAINTING_START",
  EDIT_PAINTING_SUCCESS: "EDIT_PAINTING_SUCCESS",
  EDIT_PAINTING_FAILURE: "EDIT_PAINTING_FAILURE",
  // OTHERS
  EDIT_PAINTING: "EDIT_PAINTING",
  VIEW_SELECTED_PAINTING: "VIEW_SELECTED_PAINTING",
  CLEAR_SELECTED_PAINTING: "CLEAR_SELECTED_PAINTING",
};
