export const PAINTINGS = {
  FETCH_PAINTINGS_START: "FETCH_PAINTINGS_START",
  FETCH_PAINTINGS_SUCCESS: "FETCH_PAINTINGS_SUCCESS",
  FETCH_PAINTINGS_FAILURE: "FETCH_PAINTINGS_FAILURE",
  ADD_NEW_PAINTING: "ADD_NEW_PAINTING",
  EDIT_PAINTING: "EDIT_PAINTING",
  DELETE_PAINTING: "DELETE_PAINTING",
  VIEW_SELECTED_PAINTING: "VIEW_SELECTED_PAINTING",
  CLEAR_SELECTED_PAINTING: "CLEAR_SELECTED_PAINTING",
};
